### ISSUE TITLE
[BUG] Install issue on Mac M1

### ISSUE THREAD

**Issue by spacether** [openapi-json-schema-tools/openapi-json-schema-generator#242]
#### Bug Report Checklist

- [ ] Have you provided a full/minimal spec to reproduce the issue?
- [ ] Have you validated the input using an OpenAPI validator ([example](https://apidevtools.org/swagger-parser/online/))?
- [ ] Have you tested with the latest master to confirm the issue still exists?
- [ ] Have you searched for related issues/PRs?
- [ ] What's the actual output vs expected output?
- [ ] [Optional] Sponsorship to speed up the bug fix or feature request

User @yuericlin was unable to build the java program or run the docker image

### java build
Java build: one test failing: testGetServerURLWithVariables
note: java version (20) is higher than 11

brew installed version of maven says that it was built with java 20

`
Apache Maven 3.9.4 (dfbb324ad4a7c8fb0bf182e6d91b0ae20e3d2dd9)
Maven home: /opt/homebrew/Cellar/maven/3.9.4/libexec
Java version: 20.0.2, vendor: Homebrew, runtime: /opt/homebrew/Cellar/openjdk/20.0.2/libexec/openjdk.jdk/Contents/Home
Default locale: en_US, platform encoding: UTF-8
OS name: "mac os x", version: "13.5.2", arch: "aarch64", family: "mac"
brew does not have 3.9.3
`

### system info
Chip: Apple M1 Max
macOS: 13.5.2

### docker run issue

`
docker: Error response from daemon: error creating overlay mount to /var/lib/docker/overlay2/86deda23b4fa75c8f536064cd2a1e289f3beae71592d41a3d3151d82fd3a1092-init/merged: too many levels of symbolic links.
`

##### Related issues/PRs

similar-to install issue was resolved by installing java 11
- https://github.com/openapi-json-schema-tools/openapi-json-schema-generator/issues/218

**Comment by spacether** [comment]
@yuericlin have you been able to install java 11 and get building working?

**Comment by yuericlin** [comment]
> @yuericlin have you been able to install java 11 and get building working?

no, I have not found any work-around yet. :(

**Comment by spacether** [comment]
@yuericlin can you try pulling the latest master branch and running `mvn clean package` and seeing if that works for your java 20? That works on my system using java 20.

**Comment by yuericlin** [comment]
> @yuericlin can you try pulling the latest master branch and running `mvn clean package` and seeing if that works for your java 20? That works on my system using java 20.

yes, it works now, thank you so much!

however, there were some errors in the log,
"[main] WARN com.tngtech.archunit.core.importer.ClassFileProcessor - Error during import from jrt:/java.base/java/lang/Package.class, falling back to simple import
java.lang.IllegalArgumentException: Unsupported class file major version 64"

**Comment by spacether** [comment]
That is a problem with your environment, not this software. Please work on downgrading your Java to 11 as that solved this issue previously. A different maven version may be needed.

**Comment by yuericlin** [comment]
> That is a problem with your environment, not this software. Please work on downgrading your Java to 11 as that solved this issue previously. A different maven version may be needed.

I has downgraded my java to 11.0.20.1, but the maven installed by brew was built with java 20.0.2. 
probably I need to build my own maven, :(

**Comment by spacether** [comment]
Can you look for a lower version of maven that uses Java 11?

**Comment by spacether** [comment]
Can you also delete and re-pull this image and try to use it: `openapijsonschematools/openapi-json-schema-generator-cli:latest`
I merged a PR which should remove symlinks from the denerated image, and should hopefully eliminate the `too many levels of symbolic links.` error.

**Comment by spacether** [comment]
@yuericlin if I don't hear from you in the next two weeks I will close this issue due to inactivity
- previous work shows that installing java 11 and a compatible maven version works for this issue
- I merged in 2 PRs to improve functionality here, one to allow tests to pass in java 11, and another to remove symlinks from the docker image. I do not have an m1 mac so I am unable to verify if the symlink update fixes this issue

**Comment by yuericlin** [comment]
Thank you @spacether , and sorry for the late response.

confirmed that symbolic link error is not appearing, but the other errors are still remaining, because I couldn't figure a straight forward way to downgrade maven without manually build from source (the maven build installed with brew only have java 20). btw, I did downgrade my java compiler to 11 even at the time we had the live debugging section.

**Comment by spacether** [comment]
Right but maven reports what Java it is using. When you did that maven was still using Java 20. Does docker now work for you?

**Comment by spacether** [comment]
Closing per the above feedback. @yuericlin feel free to keep responding here.
